---
  name: "release-on-feature"
  
  on:
    push:  
      branches:
        - feature*
      tags: 
        - "v*.*.*"

  jobs:
    build:
      name: "Build"
      runs-on: "ubuntu-latest"
      steps:
        - uses: actions/checkout@v3 
        - uses: actions/setup-java@v3
          with:
            java-version: '17'
            distribution: 'temurin'
        - name: Validate Gradle wrapper
          uses: gradle/wrapper-validation-action@v1
        - name: Setup Gradle
          uses: gradle/gradle-build-action@v2.7.0
          with:
            arguments: | 
              build 
              publish  
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
    semantic-release:
      name: "Semantic Release"
      needs: build
      runs-on: "ubuntu-latest"
      steps:        
        - uses: actions/upload-artifact@v3
          with:
            name: Package
            path: app/build/libs/*.jar
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.1
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}   
            release_branches: "feature.*"
        - name: Release JAR File
          uses: softprops/action-gh-release@v1
          with:
            tag_name: ${{ steps.tag_version.outputs.new_tag }}
            name: Release ${{ steps.tag_version.outputs.new_tag }}
            generate_release_notes : true
            files: app/build/libs/*.jar 

# ------------------------------------------------------------------- 