---
    name: "pull-request-on-release"
    on: 
      pull_request:
        branches:
          - release
    
    jobs:
      Build:
        name: "Build"
        runs-on: "ubuntu-latest"
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Validate Gradle wrapper
            uses: gradle/wrapper-validation-action@v1
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2.7.0
            with:
              arguments: | 
                build 
                publish  
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

      Generall-Aproval:
        name: Aprof in Generall
        runs-on: ubuntu-latest
        steps:
          - run: |
              echo A comment on PR 
          - name: Aproval in Generall of the release
            uses: trstringer/manual-approval@v1
            with:
              secret: ${{ github.TOKEN }}
              approvers: DrShadowPLay
              minimum-approvals: 1
              issue-title: "Aprove of generall functionality of ${{ github.head_ref || github.ref_name }} and the deployment to the TestSys environme"
              issue-body: "Please approve or deny the deployment of the relaese version to the TestSys environment."
              exclude-workflow-initiator-as-approver: false
              additional-approved-words: ''
              additional-denied-words: ''      

      Delpoy-on-Systest:
        name: Deploy on Systest
        runs-on: ubuntu-latest
        needs: [Generall-Aproval , Build]
        steps:
          - run: |
              echo System wird auf Systest deployed ... 
              echo System wurde erfolgreich deployed    
              echo Creating Branch
          - uses: peterjgrainger/action-create-branch@v2.0.1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              branch: 'Test-Systest_${{ github.head_ref || github.ref_name }}'

      Systest-approval:
     #    This job only runs for pull request comments
        name: Systest Aproval
        runs-on: ubuntu-latest
        needs: [Delpoy-on-Systest, Generall-Aproval]
        steps:
          - run: |
              echo A comment on PR 
          - name: Aproval for Systest
            uses: trstringer/manual-approval@v1
            with:
              secret: ${{ github.TOKEN }}
              approvers: DrShadowPLay
              minimum-approvals: 1
              issue-title: "Aprove of the functionallity ${{ github.head_ref || github.ref_name }} on TestSys environment"
              issue-body: "Please approve or deny the funcionality of the release version on the TestSys environmen"
              exclude-workflow-initiator-as-approver: false
              additional-approved-words: ''
              additional-denied-words: '' 
          - name: Delete pr-* branches
            uses: dawidd6/action-delete-branch@v3.1.0
            with:
              github_token: ${{github.token}}
              branches: Test-Systest_
              suffix: ${{ github.head_ref || github.ref_name }}
      Delpoy-on-Test:
        name: Deploy on Test
        runs-on: ubuntu-latest
        needs: Systest-approval
        steps:
          - run: |
              echo System wird auf Test deployed ...
              echo System wurde erfolgreich deployed    
              echo Creating Branch
          - uses: peterjgrainger/action-create-branch@v2.0.1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              branch: 'Test_${{ github.head_ref || github.ref_name }}'
              
      Test-aproval:
        name: Test-Aproval
        runs-on: ubuntu-latest
        needs: Delpoy-on-Test
        steps:
          - run: |
              echo A comment on PR 
          - name: Aproval for Test environment 
            uses: trstringer/manual-approval@v1
            with:
              secret: ${{ github.TOKEN }}
              approvers: DrShadowPLay
              minimum-approvals: 1
              issue-title: "Aprove of the funcionality ${{ github.head_ref || github.ref_name }} on TestSys"
              issue-body: "Please approve or deny the funcionality of the release version on the TestSys environme"
              exclude-workflow-initiator-as-approver: false
              additional-approved-words: ''
              additional-denied-words: ''            
          - name: Delete pr-* branches
            uses: dawidd6/action-delete-branch@v3.1.0
            with:
              github_token: ${{github.token}}
              branches: Test_
              suffix: ${{ github.head_ref || github.ref_name }}  