---
    name: "pull-request-on-main"
    on: 
      pull_request:
        branches:
          - main
    
    jobs:
      build:
        name: "Build"
        runs-on: "ubuntu-latest"
        steps:
          - uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            with:
              java-version: '17'
              distribution: 'temurin'
          - name: Validate Gradle wrapper
            uses: gradle/wrapper-validation-action@v1
          - name: Setup Gradle
            uses: gradle/gradle-build-action@v2.7.0
            with:
              arguments: | 
                build 
                publish  
            env:
              GITHUB_TOKEN: ${{  secrets.ACTIONS_TOKEN  }} 

      A-Aproval:
        name: Generall-Ap
        runs-on: ubuntu-latest
        steps:
          - run: |
              echo A comment on PR 
          - name: Aproval for Prodh
            uses: trstringer/manual-approval@v1
            with:
              secret: ${{ secrets.ACTIONS_TOKEN }}
              approvers: DrShadowPLay
              minimum-approvals: 1
              issue-title: "Aprove For Prodj"
              issue-body: "Please approve or deny the deployment of the relaese version to the TestSys environment."
              exclude-workflow-initiator-as-approver: false
              additional-approved-words: ''
              additional-denied-words: '' 
      
      Delpoy-on-Systest:
        name: Deploy on Prod
        runs-on: ubuntu-latest
        needs:  [build, A-Aproval]
        steps:
          - run: |
              echo System wird auf Prod deployed ... 
              echo System wurde erfolgreich deployed    
